# -*- coding: utf-8 -*-
"""Mask-RCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDK_6MWmb07SNes9h7gXvBeuyyaMay9C
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

!pip uninstall -y tensorflow

!pip install tensorflow==2.5.0

!pip install Keras==2.2.4

!pip install mrcnn

!mkdir mask_rcnn_train

from distutils.dir_util import copy_tree

copy_tree("/content/drive/My Drive/mask_rcnn_custom_train", "/content/mask_rcnn_train/")

!pwd

import os
os.chdir('/content/mask_rcnn_train/')

!pip install pycocotools

!pip uninstall pycocotools
!pip install pycocotools --no-binary :all: --no-build-isolation

!python3 train.py train --dataset=/content/mask_rcnn_train/dataset --weights=coco